
package hu.jvrs.tigris.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AfakulcsServiceBean", targetNamespace = "http://beans.services.ws.leo.jvrs.hu/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AfakulcsServiceBean {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setCrud", targetNamespace = "http://beans.services.ws.leo.jvrs.hu/", className = "hu.jvrs.tigris.wsimport.SetCrud")
    @ResponseWrapper(localName = "setCrudResponse", targetNamespace = "http://beans.services.ws.leo.jvrs.hu/", className = "hu.jvrs.tigris.wsimport.SetCrudResponse")
    public void setCrud(
        @WebParam(name = "arg0", targetNamespace = "")
        CrudService arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns hu.jvrs.tigris.wsimport.AfakulcsValaszTipus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAfakulcsById", targetNamespace = "http://beans.services.ws.leo.jvrs.hu/", className = "hu.jvrs.tigris.wsimport.GetAfakulcsById")
    @ResponseWrapper(localName = "getAfakulcsByIdResponse", targetNamespace = "http://beans.services.ws.leo.jvrs.hu/", className = "hu.jvrs.tigris.wsimport.GetAfakulcsByIdResponse")
    public AfakulcsValaszTipus getAfakulcsById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllAfakulcsKodEs", targetNamespace = "http://beans.services.ws.leo.jvrs.hu/", className = "hu.jvrs.tigris.wsimport.GetAllAfakulcsKodEs")
    @ResponseWrapper(localName = "getAllAfakulcsKodEsResponse", targetNamespace = "http://beans.services.ws.leo.jvrs.hu/", className = "hu.jvrs.tigris.wsimport.GetAllAfakulcsKodEsResponse")
    public String getAllAfakulcsKodEs();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAfakulcsKodEsById", targetNamespace = "http://beans.services.ws.leo.jvrs.hu/", className = "hu.jvrs.tigris.wsimport.GetAfakulcsKodEsById")
    @ResponseWrapper(localName = "getAfakulcsKodEsByIdResponse", targetNamespace = "http://beans.services.ws.leo.jvrs.hu/", className = "hu.jvrs.tigris.wsimport.GetAfakulcsKodEsByIdResponse")
    public String getAfakulcsKodEsById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0);

}
